### ISSUE TITLE
Add option to format timings in seconds to support current stable chrome

### ISSUE THREAD

**Issue by brandondoran** [remy/server-timings#1]
@remy this is working great! As you mentioned in the Readme, the stable version of chrome works in seconds but canary is ms. I'd like to use this in production but most of the devs on my team don't use canary and I feel like this would just cause confusion. Would accept a PR adding an option to allow the unit of measurement to be configured?  Something like this:

```javascript
// In the middleware
// default unit to milliseconds
module.exports = createTiming = ({ unit = 'milliseconds' }) => (req, res, next) => {
  ...
  // Use unit variable when calculating delta...
  ...
```

```javascript
// Usage, for when you want to override the default
const timings = require('server-timings')({ unit: 'seconds' });

app.use(timings);

// or to just use the default
const timings = require('server-timings');

app.use(timings());
```

**Comment by remy** [comment]
Sure, so long as it defaults to milliseconds as it'll land in stable in
some number of weeks.

**Comment by reel** [comment]
Is there any news on this? This is actually a bit misleading as the overall request timing is 16ms and server timing is 1.9s (example).

@brandondoran were you working on a PR or should I look into it?

**Comment by brandondoran** [comment]
@reel I was hot on this was first learned about server timings but then got busy and haven't had a chance to work on it. Now, as I think about it, I'm hesitant to put the effort in to workaround this issue that will likely be fixed in stable Chrome soon. Also, this proposal would dirty the api for something that wouldn't be needed long term and then you'd need to make another breaking change to remove it.  Seems like more trouble than it's worth.

Thoughts @remy?

**Comment by reel** [comment]
Chrome 58 is now stable. Solved! Thanks for your reply!

**Comment by remy** [comment]
lol, sorry! Glad it's live now 😂
